[build]
  command = "npm run build"  # The build command to run
  publish = "build"          # The directory to deploy (after build)

[build.environment]
  NODE_ENV = "production"    # Set the environment to production

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
